name: Compila e Crea Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nome della versione (es. v26.0.1)'
        required: true
        default: 'v26.0.1'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

     - name: Configura CMake (forzando Visual Studio 2022)
        run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Compila il progetto
        run: cmake --build build --config Release

      - name: Crea archivio ZIP del gioco
        shell: pwsh
        run: |
          # Grazie al tuo CMakeLists.txt, in build/Release trovi l'eseguibile, levels/ e assets/
          Compress-Archive -Path "build/Release/*" -DestinationPath "Puzzle3D-Windows-x64.zip"

      - name: Pubblica Release e allega il file
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: Puzzle3D-Windows-x64.zip
          generate_release_notes: true
