name: Crea Release Manuale

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Nome del tag (es. v26.0.1)'
        required: true
        default: 'v26.0.1'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Crea la Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          generate_release_notes: true
